module.exports = {
  COOKIE: "CTSWW-fbiQJxnkvtBdKJt9lm0_0hC7mJCpcsmQ17b5okf_Dy8KowuBzcbluJ5344-v5R7_-c9EETMjCTDiXJzR2pwzaOAPAVdmlb75nmUFV5TnvJhTyfZYs4eO6vfqm3",
  EMAIL: "1403303221@qq.com",
  AUTHORIZATION_CODE: process.env.AUTHORIZATION_CODE,
  PUSHPLUS_TOKEN: process.env.PUSHPLUS_TOKEN,
  DINGDING_WEBHOOK: process.env.DINGDING_WEBHOOK,
  FEISHU_WEBHOOK: process.env.FEISHU_WEBHOOK,
}
